4 featureweb scraping
Asifdotexe/AniMate pull request #5
Opened 2024-07-28 12:46 UTC by Asifdotexe

2024-07-28 17:14 UTC, str04 requested changes

2024-07-28 17:14 UTC, str04 commented on code/webscraping/SCRAPER.md
> +  - `month`: A string representing the month.
test comment

2024-07-28 17:15 UTC, Asifdotexe commented on code/webscraping/SCRAPER.md
> +  - `month`: A string representing the month.
acknowledged

2024-07-28 17:20 UTC, PranjalDhamane approved these changes

2024-07-28 17:37 UTC, str04 approved these changes
I approve the code.

2024-07-29 04:14 UTC, tanvisivaraj approved these changes

2024-07-29 04:18 UTC, merged