7 data preprocessing
Asifdotexe/AniMate pull request #8
Opened 2024-08-11 09:57 UTC by PranjalDhamane

Dear All,

I have completed preprocessing from my side but before that please review and if there are some suggestions or changes required do let me know. 

@Asifdotexe 
@str04 
@aditimane07 
@tanvisivaraj

2024-08-11 14:48 UTC, Asifdotexe requested changes
Made some changes. please make sure you intregrate them

2024-08-11 14:48 UTC, Asifdotexe commented on code/notebook/issue-7-pd-data-processing.ipynb
> +    "df = df.query(\"genres not in ['Ecchi', 'Hentai', 'Erotica']\")\n",
Still there are instances of Ecchi and other mature content present

2024-08-11 14:48 UTC, Asifdotexe commented on code/notebook/src/cleaning.py
> +def nlp_cleaning(text):
Add the code for removing special character as well, the title contains some special characters in them.
all the non ASCII values should be removed, refer to the image below

in the title

![image](https://github.com/user-attachments/assets/df9b042e-9379-485b-808e-05215d676d71)

2024-08-11 14:48 UTC, Asifdotexe commented on code/notebook/src/cleaning.py
> +    if not isinstance(text, str):
Can we do the following preprocessing on the episode column.

I have seen that the data has a lot of missing values but there is a pattern to it. 
Movies are usually just individual pieces of media and don't usually have episodes hence in that case, we do not have the episode count populated.

Can we do imputation on the records where we can find "movie" in the title, the value should be filled as 1

2024-08-11 14:48 UTC, Asifdotexe commented on code/notebook/src/cleaning.py
> +    if not isinstance(text, str):
After this, we can populate the rest of the missing values as -1

2024-08-25 13:03 UTC, Asifdotexe submitted a review, later dismissed
Looks good to me

2024-08-26 04:13 UTC, aditimane07 submitted a review, later dismissed

2024-08-26 15:31 UTC, str04 approved these changes
It looks good to me also.

2024-08-27 06:50 UTC, Asifdotexe commented
The branch was being merged with main, refrain from doing that. All the changes needs to be initially pushed to #3 develop branch. 

The idea behind this is, we will be treating it as staging area for integrating the changes. As we are programming in different modules. 

Once we are able to run it on develop bug free / with minimal bugs then we will be pushing the code to main to conclude on release.

@aditimane07 
@str04 
@tanvisivaraj 
@PranjalDhamane 

While creating pull requests, make sure you are asking to merge on #3 develop branch instead of main

2024-08-27 16:26 UTC, merged